sudo: required
services:
  - docker
  - mongodb
language: go
go:
  - "1.11"
env:
  - TRAVIS=1 GO111MODULES=on
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin
  - make test
  - make build
  - make push
branches:
  only:
    - master
