version: '3.5'
networks:
    mongodb:
        driver: bridge
        internal: true
services:
    mongodb:
        image: 'mongo:3.4'
        restart: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASS}'
            MONGO_INITDB_DATABASE: samplist
        volumes:
            - '${DATA_DIR}/${COMPOSE_PROJECT_NAME}/mongodb:/data/db'
        networks:
            - mongodb
        labels:
            - traefik.enable=false
    samp-servers-api:
        image: 'southclaws/samp-servers-api:1.6.1'
        restart: on-failure
        environment:
            SAMPLIST_BIND: '0.0.0.0:80'
            SAMPLIST_MONGO_USER: '${MONGO_USER}'
            SAMPLIST_MONGO_PASS: '${MONGO_PASS}'
            SAMPLIST_MONGO_HOST: mongodb
            SAMPLIST_MONGO_PORT: '27017'
            SAMPLIST_MONGO_NAME: samplist
            SAMPLIST_MONGO_COLLECTION: servers
            SAMPLIST_QUERY_INTERVAL: '120s'
            SAMPLIST_MAX_FAILED_QUERY: '10'
            SAMPLIST_VERIFY_BY_HOST: 'true'
        networks:
            - default
            - mongodb
        depends_on:
            - mongodb
        labels:
            - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_default'
            - 'traefik.frontend.rule=Host:api.samp-servers.net'
            - 'traefik.frontend.headers.SSLRedirect=true'
            - 'traefik.port=80'
    samp-servers-frontend:
        image: 'southclaws/samp-servers-frontend:1.3.3'
        restart: on-failure
        networks:
            - default
        labels:
            - 'traefik.docker.network=${COMPOSE_PROJECT_NAME}_default'
            - 'traefik.frontend.rule=Host:samp-servers.net'
            - 'traefik.frontend.headers.SSLRedirect=true'
